Chore(githooks): edit hooks for better experience

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,5 +1,18 @@
 #!/usr/bin/env bash
 
 printf "\e[33;1m%s\e[0m\n" 'Running the Flutter formatter'
-dart format --output=none --set-exit-if-changed .
+flutter format --output=none --set-exit-if-changed .
 printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter formatter'
+
+if [[ `git status --porcelain` ]]; then
+  printf "\e[31;1m%s\e[0m\n" 'This script needs to run against committed code only. Please commit or stash you changes.'
+  exit 1
+fi
+printf "\e[33;1m%s\e[0m\n" 'Running the Flutter analyzer'
+
+flutter analyze
+if [ $? -ne 0 ]; then
+  printf "\e[31;1m%s\e[0m\n" 'Flutter analyzer error'
+  exit 1
+fi
+printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter analyzer'
